version: "3"
services:
  homepage:
    # mkdir -p /services/config/homepage
    #
    # 80 : web
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    ports:
      - 80:3000
    volumes:
      - /services/config/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro

  jellyfin:
    # mkdir -p /services/config/jellyfin
    # mkdir -p /services/data/music
    #
    # 8096 : web admin
    # 1900 : DNLA / UPnP
    image: jellyfin/jellyfin:latest
    restart: unless-stopped
    network_mode: "host"
    ports:
      - 8096:8096
      - 1900:1900
    volumes:
      - /services/config/jellyfin:/config
      - /services/data/music:/music
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      - homepage.group=Media
      - homepage.name=Jellyfin
      - homepage.icon=jellyfin.png
      - homepage.href=http://home:8096/
      - homepage.description=Media server
