# mkdir -p /services/config/jellyfin
# mkdir -p /services/data/music
# 
# 8086 : web admin
# 1900 : DNLA / UPnP 

version: '3'
services:
  jellyfin:
    image: jellyfin/jellyfin
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - /services/config/jellyfin:/config
      - /services/data/music:/music
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      - homepage.group=Media
      - homepage.name=Jellyfin
      - homepage.icon=jellyfin.png
      - homepage.href=http://home:8096/
      - homepage.description=Media server

